name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
env:
  go-version: 1.15
jobs:
  test:
    name: Small test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - run: go build .
      - run: go test -race -v -count 1 .
      - run: go vet .
