name: CI
on:
  pull_request:
  push:
    branches:
      - 'main'
env:
  go-version: 1.19
jobs:
  test:
    name: Small test
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - run: go build .
      - run: go test -race -v -count 1 .
      - run: go vet .
      - name: staticcheck
        run: |
          mkdir -p bin
          GOBIN=$(pwd)/bin go install honnef.co/go/tools/cmd/staticcheck@latest
          ./bin/staticcheck .
